/// <reference types="next" />
/// <reference types="next/image-types/global" />
// oxlint-disable-next-line typescript/triple-slash-reference -- Generated by Next.js for typed routes.
/// <reference path="./.next/types/routes.d.ts" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.
